### ISSUE TITLE
Apply styles on Remark component.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#63]
This is mainly the same design as #64  but without no receiver field.

**Comment by goldsteinsveta** [comment]
something like this:
<img width="850" alt="Screenshot 2021-04-21 at 16 30 50" src="https://user-images.githubusercontent.com/8782596/115571192-103fc500-a2bf-11eb-8a61-ce8fbc1be2cf.png">

Because we do not have a receiver here, I really felt like we need a header "Remark Source → Target" summarising what is going on here. So Transfer screen will have to wear it too

**Comment by hbulgarini** [comment]
> Because we do not have a receiver here, I really felt like we need a header "Remark Source → Target" summarising what is going on here. So Transfer screen will have to wear it too.

Definitely we need this. Actually in the design provided i cannot say if the polkadot icon is correct because i'm not able to see if polkadot is the target chain.
